name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: "${{ matrix.os }}-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        submodules: true

    - uses: lukka/get-cmake@latest
    - uses: lukka/run-vcpkg@v10

    - name: Build
      uses: lukka/run-cmake@v10
      with:
        workflowPreset: "${{ matrix.os }}-ci"
